### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by mrmikeo** [num8er/sails-hook-mongo-index#1]

**Comment by num8er** [comment]
@mrmikeo how You're using it? also how You've checked indexes? 

1. You've to install it
2. You've to define index in schema

it's based on this manual: https://sailsjs.com/documentation/concepts/extending-sails/hooks/installable-hooks and I used it in production

to get better support please provide steps to reproduce to solve Your problem

**Comment by num8er** [comment]
not enough details, please reopen or create new issue with details
